// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package storage

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countArtifactVersions = `-- name: CountArtifactVersions :one
SELECT COUNT(*) FROM artifact_versions
WHERE artifact_id = $1
`

func (q *Queries) CountArtifactVersions(ctx context.Context, artifactID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArtifactVersions, artifactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (user_id, exercise_id, name, content)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, exercise_id, name, content, created_at, updated_at
`

type CreateArtifactParams struct {
	UserID     uuid.UUID       `db:"user_id" json:"user_id"`
	ExerciseID sql.NullString  `db:"exercise_id" json:"exercise_id"`
	Name       string          `db:"name" json:"name"`
	Content    json.RawMessage `db:"content" json:"content"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.UserID,
		arg.ExerciseID,
		arg.Name,
		arg.Content,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createArtifactVersion = `-- name: CreateArtifactVersion :one
INSERT INTO artifact_versions (artifact_id, version, content)
VALUES ($1, $2, $3)
RETURNING id, artifact_id, version, content, created_at
`

type CreateArtifactVersionParams struct {
	ArtifactID uuid.UUID       `db:"artifact_id" json:"artifact_id"`
	Version    int32           `db:"version" json:"version"`
	Content    json.RawMessage `db:"content" json:"content"`
}

func (q *Queries) CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRowContext(ctx, createArtifactVersion, arg.ArtifactID, arg.Version, arg.Content)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts
WHERE id = $1 AND user_id = $2
`

type DeleteArtifactParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) error {
	_, err := q.db.ExecContext(ctx, deleteArtifact, arg.ID, arg.UserID)
	return err
}

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT id, user_id, exercise_id, name, content, created_at, updated_at FROM artifacts
WHERE id = $1
`

func (q *Queries) GetArtifactByID(ctx context.Context, id uuid.UUID) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByID, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactByIDAndUser = `-- name: GetArtifactByIDAndUser :one
SELECT id, user_id, exercise_id, name, content, created_at, updated_at FROM artifacts
WHERE id = $1 AND user_id = $2
`

type GetArtifactByIDAndUserParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetArtifactByIDAndUser(ctx context.Context, arg GetArtifactByIDAndUserParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByIDAndUser, arg.ID, arg.UserID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactVersion = `-- name: GetArtifactVersion :one
SELECT id, artifact_id, version, content, created_at FROM artifact_versions
WHERE artifact_id = $1 AND version = $2
`

type GetArtifactVersionParams struct {
	ArtifactID uuid.UUID `db:"artifact_id" json:"artifact_id"`
	Version    int32     `db:"version" json:"version"`
}

func (q *Queries) GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRowContext(ctx, getArtifactVersion, arg.ArtifactID, arg.Version)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestArtifactVersion = `-- name: GetLatestArtifactVersion :one
SELECT id, artifact_id, version, content, created_at FROM artifact_versions
WHERE artifact_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestArtifactVersion(ctx context.Context, artifactID uuid.UUID) (ArtifactVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestArtifactVersion, artifactID)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactVersions = `-- name: ListArtifactVersions :many
SELECT id, artifact_id, version, content, created_at FROM artifact_versions
WHERE artifact_id = $1
ORDER BY version DESC
LIMIT $2
`

type ListArtifactVersionsParams struct {
	ArtifactID uuid.UUID `db:"artifact_id" json:"artifact_id"`
	Limit      int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ArtifactVersion, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactVersions, arg.ArtifactID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactVersion{}
	for rows.Next() {
		var i ArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByExercise = `-- name: ListArtifactsByExercise :many
SELECT id, user_id, exercise_id, name, content, created_at, updated_at FROM artifacts
WHERE user_id = $1 AND exercise_id = $2
ORDER BY updated_at DESC
`

type ListArtifactsByExerciseParams struct {
	UserID     uuid.UUID      `db:"user_id" json:"user_id"`
	ExerciseID sql.NullString `db:"exercise_id" json:"exercise_id"`
}

func (q *Queries) ListArtifactsByExercise(ctx context.Context, arg ListArtifactsByExerciseParams) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByExercise, arg.UserID, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByUser = `-- name: ListArtifactsByUser :many
SELECT id, user_id, exercise_id, name, content, created_at, updated_at FROM artifacts
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListArtifactsByUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListArtifactsByUser(ctx context.Context, arg ListArtifactsByUserParams) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifact = `-- name: UpdateArtifact :one
UPDATE artifacts
SET name = COALESCE($3, name),
    content = COALESCE($4, content)
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, exercise_id, name, content, created_at, updated_at
`

type UpdateArtifactParams struct {
	ID      uuid.UUID             `db:"id" json:"id"`
	UserID  uuid.UUID             `db:"user_id" json:"user_id"`
	Name    sql.NullString        `db:"name" json:"name"`
	Content pqtype.NullRawMessage `db:"content" json:"content"`
}

func (q *Queries) UpdateArtifact(ctx context.Context, arg UpdateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, updateArtifact,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Content,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtifactContent = `-- name: UpdateArtifactContent :one
UPDATE artifacts
SET content = $2
WHERE id = $1
RETURNING id, user_id, exercise_id, name, content, created_at, updated_at
`

type UpdateArtifactContentParams struct {
	ID      uuid.UUID       `db:"id" json:"id"`
	Content json.RawMessage `db:"content" json:"content"`
}

func (q *Queries) UpdateArtifactContent(ctx context.Context, arg UpdateArtifactContentParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, updateArtifactContent, arg.ID, arg.Content)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
