// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package storage

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countEventsByType = `-- name: CountEventsByType :one
SELECT COUNT(*) FROM events
WHERE event_type = $1
AND created_at >= $2
`

type CountEventsByTypeParams struct {
	EventType string    `db:"event_type" json:"event_type"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CountEventsByType(ctx context.Context, arg CountEventsByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsByType, arg.EventType, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (user_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, user_id, event_type, payload, created_at
`

type CreateEventParams struct {
	UserID    uuid.NullUUID   `db:"user_id" json:"user_id"`
	EventType string          `db:"event_type" json:"event_type"`
	Payload   json.RawMessage `db:"payload" json:"payload"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.UserID, arg.EventType, arg.Payload)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByType = `-- name: ListEventsByType :many
SELECT id, user_id, event_type, payload, created_at FROM events
WHERE event_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsByTypeParams struct {
	EventType string `db:"event_type" json:"event_type"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListEventsByType(ctx context.Context, arg ListEventsByTypeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByType, arg.EventType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByUser = `-- name: ListEventsByUser :many
SELECT id, user_id, event_type, payload, created_at FROM events
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsByUserParams struct {
	UserID uuid.NullUUID `db:"user_id" json:"user_id"`
	Limit  int32         `db:"limit" json:"limit"`
	Offset int32         `db:"offset" json:"offset"`
}

func (q *Queries) ListEventsByUser(ctx context.Context, arg ListEventsByUserParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
