// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Artifact struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	UserID     uuid.UUID       `db:"user_id" json:"user_id"`
	ExerciseID sql.NullString  `db:"exercise_id" json:"exercise_id"`
	Name       string          `db:"name" json:"name"`
	Content    json.RawMessage `db:"content" json:"content"`
	CreatedAt  time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time       `db:"updated_at" json:"updated_at"`
}

type ArtifactVersion struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	ArtifactID uuid.UUID       `db:"artifact_id" json:"artifact_id"`
	Version    int32           `db:"version" json:"version"`
	Content    json.RawMessage `db:"content" json:"content"`
	CreatedAt  time.Time       `db:"created_at" json:"created_at"`
}

type Event struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	UserID    uuid.NullUUID   `db:"user_id" json:"user_id"`
	EventType string          `db:"event_type" json:"event_type"`
	Payload   json.RawMessage `db:"payload" json:"payload"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

type Intervention struct {
	ID          uuid.UUID             `db:"id" json:"id"`
	SessionID   uuid.UUID             `db:"session_id" json:"session_id"`
	UserID      uuid.UUID             `db:"user_id" json:"user_id"`
	RunID       uuid.NullUUID         `db:"run_id" json:"run_id"`
	Intent      string                `db:"intent" json:"intent"`
	Level       int32                 `db:"level" json:"level"`
	Type        string                `db:"type" json:"type"`
	Content     string                `db:"content" json:"content"`
	Targets     pqtype.NullRawMessage `db:"targets" json:"targets"`
	Rationale   sql.NullString        `db:"rationale" json:"rationale"`
	RequestedAt time.Time             `db:"requested_at" json:"requested_at"`
	DeliveredAt time.Time             `db:"delivered_at" json:"delivered_at"`
}

type LearningProfile struct {
	ID               uuid.UUID       `db:"id" json:"id"`
	UserID           uuid.UUID       `db:"user_id" json:"user_id"`
	TopicSkills      json.RawMessage `db:"topic_skills" json:"topic_skills"`
	TotalExercises   int32           `db:"total_exercises" json:"total_exercises"`
	TotalRuns        int32           `db:"total_runs" json:"total_runs"`
	HintRequests     int32           `db:"hint_requests" json:"hint_requests"`
	AvgTimeToGreenMs sql.NullInt64   `db:"avg_time_to_green_ms" json:"avg_time_to_green_ms"`
	CommonErrors     []string        `db:"common_errors" json:"common_errors"`
	UpdatedAt        time.Time       `db:"updated_at" json:"updated_at"`
}

type PairingSession struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	UserID     uuid.UUID       `db:"user_id" json:"user_id"`
	ArtifactID uuid.NullUUID   `db:"artifact_id" json:"artifact_id"`
	ExerciseID sql.NullString  `db:"exercise_id" json:"exercise_id"`
	Policy     json.RawMessage `db:"policy" json:"policy"`
	StartedAt  time.Time       `db:"started_at" json:"started_at"`
	EndedAt    sql.NullTime    `db:"ended_at" json:"ended_at"`
}

type Run struct {
	ID         uuid.UUID             `db:"id" json:"id"`
	ArtifactID uuid.UUID             `db:"artifact_id" json:"artifact_id"`
	UserID     uuid.UUID             `db:"user_id" json:"user_id"`
	ExerciseID sql.NullString        `db:"exercise_id" json:"exercise_id"`
	Status     string                `db:"status" json:"status"`
	Recipe     json.RawMessage       `db:"recipe" json:"recipe"`
	Output     pqtype.NullRawMessage `db:"output" json:"output"`
	StartedAt  sql.NullTime          `db:"started_at" json:"started_at"`
	FinishedAt sql.NullTime          `db:"finished_at" json:"finished_at"`
	CreatedAt  time.Time             `db:"created_at" json:"created_at"`
}

type Session struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	Email        string         `db:"email" json:"email"`
	Name         sql.NullString `db:"name" json:"name"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
}
