// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pairing.sql

package storage

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countInterventionsBySession = `-- name: CountInterventionsBySession :one
SELECT COUNT(*) FROM interventions
WHERE session_id = $1
`

func (q *Queries) CountInterventionsBySession(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInterventionsBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIntervention = `-- name: CreateIntervention :one
INSERT INTO interventions (
    session_id, user_id, run_id, intent, level, type,
    content, targets, rationale, requested_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, session_id, user_id, run_id, intent, level, type, content, targets, rationale, requested_at, delivered_at
`

type CreateInterventionParams struct {
	SessionID   uuid.UUID             `db:"session_id" json:"session_id"`
	UserID      uuid.UUID             `db:"user_id" json:"user_id"`
	RunID       uuid.NullUUID         `db:"run_id" json:"run_id"`
	Intent      string                `db:"intent" json:"intent"`
	Level       int32                 `db:"level" json:"level"`
	Type        string                `db:"type" json:"type"`
	Content     string                `db:"content" json:"content"`
	Targets     pqtype.NullRawMessage `db:"targets" json:"targets"`
	Rationale   sql.NullString        `db:"rationale" json:"rationale"`
	RequestedAt time.Time             `db:"requested_at" json:"requested_at"`
}

func (q *Queries) CreateIntervention(ctx context.Context, arg CreateInterventionParams) (Intervention, error) {
	row := q.db.QueryRowContext(ctx, createIntervention,
		arg.SessionID,
		arg.UserID,
		arg.RunID,
		arg.Intent,
		arg.Level,
		arg.Type,
		arg.Content,
		arg.Targets,
		arg.Rationale,
		arg.RequestedAt,
	)
	var i Intervention
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.RunID,
		&i.Intent,
		&i.Level,
		&i.Type,
		&i.Content,
		&i.Targets,
		&i.Rationale,
		&i.RequestedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const createPairingSession = `-- name: CreatePairingSession :one
INSERT INTO pairing_sessions (user_id, artifact_id, exercise_id, policy)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, artifact_id, exercise_id, policy, started_at, ended_at
`

type CreatePairingSessionParams struct {
	UserID     uuid.UUID       `db:"user_id" json:"user_id"`
	ArtifactID uuid.NullUUID   `db:"artifact_id" json:"artifact_id"`
	ExerciseID sql.NullString  `db:"exercise_id" json:"exercise_id"`
	Policy     json.RawMessage `db:"policy" json:"policy"`
}

func (q *Queries) CreatePairingSession(ctx context.Context, arg CreatePairingSessionParams) (PairingSession, error) {
	row := q.db.QueryRowContext(ctx, createPairingSession,
		arg.UserID,
		arg.ArtifactID,
		arg.ExerciseID,
		arg.Policy,
	)
	var i PairingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtifactID,
		&i.ExerciseID,
		&i.Policy,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const endPairingSession = `-- name: EndPairingSession :one
UPDATE pairing_sessions
SET ended_at = NOW()
WHERE id = $1
RETURNING id, user_id, artifact_id, exercise_id, policy, started_at, ended_at
`

func (q *Queries) EndPairingSession(ctx context.Context, id uuid.UUID) (PairingSession, error) {
	row := q.db.QueryRowContext(ctx, endPairingSession, id)
	var i PairingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtifactID,
		&i.ExerciseID,
		&i.Policy,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getActivePairingSession = `-- name: GetActivePairingSession :one
SELECT id, user_id, artifact_id, exercise_id, policy, started_at, ended_at FROM pairing_sessions
WHERE user_id = $1 AND ended_at IS NULL
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActivePairingSession(ctx context.Context, userID uuid.UUID) (PairingSession, error) {
	row := q.db.QueryRowContext(ctx, getActivePairingSession, userID)
	var i PairingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtifactID,
		&i.ExerciseID,
		&i.Policy,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getInterventionByID = `-- name: GetInterventionByID :one
SELECT id, session_id, user_id, run_id, intent, level, type, content, targets, rationale, requested_at, delivered_at FROM interventions
WHERE id = $1
`

func (q *Queries) GetInterventionByID(ctx context.Context, id uuid.UUID) (Intervention, error) {
	row := q.db.QueryRowContext(ctx, getInterventionByID, id)
	var i Intervention
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.RunID,
		&i.Intent,
		&i.Level,
		&i.Type,
		&i.Content,
		&i.Targets,
		&i.Rationale,
		&i.RequestedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getLastInterventionBySession = `-- name: GetLastInterventionBySession :one
SELECT id, session_id, user_id, run_id, intent, level, type, content, targets, rationale, requested_at, delivered_at FROM interventions
WHERE session_id = $1
ORDER BY delivered_at DESC
LIMIT 1
`

func (q *Queries) GetLastInterventionBySession(ctx context.Context, sessionID uuid.UUID) (Intervention, error) {
	row := q.db.QueryRowContext(ctx, getLastInterventionBySession, sessionID)
	var i Intervention
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.RunID,
		&i.Intent,
		&i.Level,
		&i.Type,
		&i.Content,
		&i.Targets,
		&i.Rationale,
		&i.RequestedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getPairingSession = `-- name: GetPairingSession :one
SELECT id, user_id, artifact_id, exercise_id, policy, started_at, ended_at FROM pairing_sessions
WHERE id = $1
`

func (q *Queries) GetPairingSession(ctx context.Context, id uuid.UUID) (PairingSession, error) {
	row := q.db.QueryRowContext(ctx, getPairingSession, id)
	var i PairingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtifactID,
		&i.ExerciseID,
		&i.Policy,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listInterventionsBySession = `-- name: ListInterventionsBySession :many
SELECT id, session_id, user_id, run_id, intent, level, type, content, targets, rationale, requested_at, delivered_at FROM interventions
WHERE session_id = $1
ORDER BY delivered_at DESC
LIMIT $2
`

type ListInterventionsBySessionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	Limit     int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListInterventionsBySession(ctx context.Context, arg ListInterventionsBySessionParams) ([]Intervention, error) {
	rows, err := q.db.QueryContext(ctx, listInterventionsBySession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Intervention{}
	for rows.Next() {
		var i Intervention
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.RunID,
			&i.Intent,
			&i.Level,
			&i.Type,
			&i.Content,
			&i.Targets,
			&i.Rationale,
			&i.RequestedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterventionsByUser = `-- name: ListInterventionsByUser :many
SELECT id, session_id, user_id, run_id, intent, level, type, content, targets, rationale, requested_at, delivered_at FROM interventions
WHERE user_id = $1
ORDER BY delivered_at DESC
LIMIT $2 OFFSET $3
`

type ListInterventionsByUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListInterventionsByUser(ctx context.Context, arg ListInterventionsByUserParams) ([]Intervention, error) {
	rows, err := q.db.QueryContext(ctx, listInterventionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Intervention{}
	for rows.Next() {
		var i Intervention
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.RunID,
			&i.Intent,
			&i.Level,
			&i.Type,
			&i.Content,
			&i.Targets,
			&i.Rationale,
			&i.RequestedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
