// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package storage

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createLearningProfile = `-- name: CreateLearningProfile :one
INSERT INTO learning_profiles (user_id)
VALUES ($1)
RETURNING id, user_id, topic_skills, total_exercises, total_runs, hint_requests, avg_time_to_green_ms, common_errors, updated_at
`

func (q *Queries) CreateLearningProfile(ctx context.Context, userID uuid.UUID) (LearningProfile, error) {
	row := q.db.QueryRowContext(ctx, createLearningProfile, userID)
	var i LearningProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicSkills,
		&i.TotalExercises,
		&i.TotalRuns,
		&i.HintRequests,
		&i.AvgTimeToGreenMs,
		pq.Array(&i.CommonErrors),
		&i.UpdatedAt,
	)
	return i, err
}

const getLearningProfile = `-- name: GetLearningProfile :one
SELECT id, user_id, topic_skills, total_exercises, total_runs, hint_requests, avg_time_to_green_ms, common_errors, updated_at FROM learning_profiles
WHERE user_id = $1
`

func (q *Queries) GetLearningProfile(ctx context.Context, userID uuid.UUID) (LearningProfile, error) {
	row := q.db.QueryRowContext(ctx, getLearningProfile, userID)
	var i LearningProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicSkills,
		&i.TotalExercises,
		&i.TotalRuns,
		&i.HintRequests,
		&i.AvgTimeToGreenMs,
		pq.Array(&i.CommonErrors),
		&i.UpdatedAt,
	)
	return i, err
}

const incrementProfileHints = `-- name: IncrementProfileHints :one
UPDATE learning_profiles
SET hint_requests = hint_requests + 1
WHERE user_id = $1
RETURNING id, user_id, topic_skills, total_exercises, total_runs, hint_requests, avg_time_to_green_ms, common_errors, updated_at
`

func (q *Queries) IncrementProfileHints(ctx context.Context, userID uuid.UUID) (LearningProfile, error) {
	row := q.db.QueryRowContext(ctx, incrementProfileHints, userID)
	var i LearningProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicSkills,
		&i.TotalExercises,
		&i.TotalRuns,
		&i.HintRequests,
		&i.AvgTimeToGreenMs,
		pq.Array(&i.CommonErrors),
		&i.UpdatedAt,
	)
	return i, err
}

const incrementProfileRuns = `-- name: IncrementProfileRuns :one
UPDATE learning_profiles
SET total_runs = total_runs + 1
WHERE user_id = $1
RETURNING id, user_id, topic_skills, total_exercises, total_runs, hint_requests, avg_time_to_green_ms, common_errors, updated_at
`

func (q *Queries) IncrementProfileRuns(ctx context.Context, userID uuid.UUID) (LearningProfile, error) {
	row := q.db.QueryRowContext(ctx, incrementProfileRuns, userID)
	var i LearningProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicSkills,
		&i.TotalExercises,
		&i.TotalRuns,
		&i.HintRequests,
		&i.AvgTimeToGreenMs,
		pq.Array(&i.CommonErrors),
		&i.UpdatedAt,
	)
	return i, err
}

const updateLearningProfileStats = `-- name: UpdateLearningProfileStats :one
UPDATE learning_profiles
SET total_exercises = COALESCE($2, total_exercises),
    total_runs = COALESCE($3, total_runs),
    hint_requests = COALESCE($4, hint_requests),
    avg_time_to_green_ms = COALESCE($5, avg_time_to_green_ms),
    common_errors = COALESCE($6, common_errors)
WHERE user_id = $1
RETURNING id, user_id, topic_skills, total_exercises, total_runs, hint_requests, avg_time_to_green_ms, common_errors, updated_at
`

type UpdateLearningProfileStatsParams struct {
	UserID           uuid.UUID     `db:"user_id" json:"user_id"`
	TotalExercises   sql.NullInt32 `db:"total_exercises" json:"total_exercises"`
	TotalRuns        sql.NullInt32 `db:"total_runs" json:"total_runs"`
	HintRequests     sql.NullInt32 `db:"hint_requests" json:"hint_requests"`
	AvgTimeToGreenMs sql.NullInt64 `db:"avg_time_to_green_ms" json:"avg_time_to_green_ms"`
	CommonErrors     []string      `db:"common_errors" json:"common_errors"`
}

func (q *Queries) UpdateLearningProfileStats(ctx context.Context, arg UpdateLearningProfileStatsParams) (LearningProfile, error) {
	row := q.db.QueryRowContext(ctx, updateLearningProfileStats,
		arg.UserID,
		arg.TotalExercises,
		arg.TotalRuns,
		arg.HintRequests,
		arg.AvgTimeToGreenMs,
		pq.Array(arg.CommonErrors),
	)
	var i LearningProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicSkills,
		&i.TotalExercises,
		&i.TotalRuns,
		&i.HintRequests,
		&i.AvgTimeToGreenMs,
		pq.Array(&i.CommonErrors),
		&i.UpdatedAt,
	)
	return i, err
}

const updateTopicSkills = `-- name: UpdateTopicSkills :one
UPDATE learning_profiles
SET topic_skills = $2
WHERE user_id = $1
RETURNING id, user_id, topic_skills, total_exercises, total_runs, hint_requests, avg_time_to_green_ms, common_errors, updated_at
`

type UpdateTopicSkillsParams struct {
	UserID      uuid.UUID       `db:"user_id" json:"user_id"`
	TopicSkills json.RawMessage `db:"topic_skills" json:"topic_skills"`
}

func (q *Queries) UpdateTopicSkills(ctx context.Context, arg UpdateTopicSkillsParams) (LearningProfile, error) {
	row := q.db.QueryRowContext(ctx, updateTopicSkills, arg.UserID, arg.TopicSkills)
	var i LearningProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicSkills,
		&i.TotalExercises,
		&i.TotalRuns,
		&i.HintRequests,
		&i.AvgTimeToGreenMs,
		pq.Array(&i.CommonErrors),
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLearningProfile = `-- name: UpsertLearningProfile :one
INSERT INTO learning_profiles (user_id, topic_skills, total_exercises, total_runs, hint_requests)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET topic_skills = EXCLUDED.topic_skills,
    total_exercises = EXCLUDED.total_exercises,
    total_runs = EXCLUDED.total_runs,
    hint_requests = EXCLUDED.hint_requests
RETURNING id, user_id, topic_skills, total_exercises, total_runs, hint_requests, avg_time_to_green_ms, common_errors, updated_at
`

type UpsertLearningProfileParams struct {
	UserID         uuid.UUID       `db:"user_id" json:"user_id"`
	TopicSkills    json.RawMessage `db:"topic_skills" json:"topic_skills"`
	TotalExercises int32           `db:"total_exercises" json:"total_exercises"`
	TotalRuns      int32           `db:"total_runs" json:"total_runs"`
	HintRequests   int32           `db:"hint_requests" json:"hint_requests"`
}

func (q *Queries) UpsertLearningProfile(ctx context.Context, arg UpsertLearningProfileParams) (LearningProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertLearningProfile,
		arg.UserID,
		arg.TopicSkills,
		arg.TotalExercises,
		arg.TotalRuns,
		arg.HintRequests,
	)
	var i LearningProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicSkills,
		&i.TotalExercises,
		&i.TotalRuns,
		&i.HintRequests,
		&i.AvgTimeToGreenMs,
		pq.Array(&i.CommonErrors),
		&i.UpdatedAt,
	)
	return i, err
}
