// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountArtifactVersions(ctx context.Context, artifactID uuid.UUID) (int64, error)
	CountEventsByType(ctx context.Context, arg CountEventsByTypeParams) (int64, error)
	CountInterventionsBySession(ctx context.Context, sessionID uuid.UUID) (int64, error)
	CountRunsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountSuccessfulRunsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (ArtifactVersion, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateIntervention(ctx context.Context, arg CreateInterventionParams) (Intervention, error)
	CreateLearningProfile(ctx context.Context, userID uuid.UUID) (LearningProfile, error)
	CreatePairingSession(ctx context.Context, arg CreatePairingSessionParams) (PairingSession, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	EndPairingSession(ctx context.Context, id uuid.UUID) (PairingSession, error)
	GetActivePairingSession(ctx context.Context, userID uuid.UUID) (PairingSession, error)
	GetArtifactByID(ctx context.Context, id uuid.UUID) (Artifact, error)
	GetArtifactByIDAndUser(ctx context.Context, arg GetArtifactByIDAndUserParams) (Artifact, error)
	GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (ArtifactVersion, error)
	GetInterventionByID(ctx context.Context, id uuid.UUID) (Intervention, error)
	GetLastInterventionBySession(ctx context.Context, sessionID uuid.UUID) (Intervention, error)
	GetLatestArtifactVersion(ctx context.Context, artifactID uuid.UUID) (ArtifactVersion, error)
	GetLearningProfile(ctx context.Context, userID uuid.UUID) (LearningProfile, error)
	GetPairingSession(ctx context.Context, id uuid.UUID) (PairingSession, error)
	GetRunByID(ctx context.Context, id uuid.UUID) (Run, error)
	GetRunByIDAndUser(ctx context.Context, arg GetRunByIDAndUserParams) (Run, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	IncrementProfileHints(ctx context.Context, userID uuid.UUID) (LearningProfile, error)
	IncrementProfileRuns(ctx context.Context, userID uuid.UUID) (LearningProfile, error)
	ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ArtifactVersion, error)
	ListArtifactsByExercise(ctx context.Context, arg ListArtifactsByExerciseParams) ([]Artifact, error)
	ListArtifactsByUser(ctx context.Context, arg ListArtifactsByUserParams) ([]Artifact, error)
	ListEventsByType(ctx context.Context, arg ListEventsByTypeParams) ([]Event, error)
	ListEventsByUser(ctx context.Context, arg ListEventsByUserParams) ([]Event, error)
	ListInterventionsBySession(ctx context.Context, arg ListInterventionsBySessionParams) ([]Intervention, error)
	ListInterventionsByUser(ctx context.Context, arg ListInterventionsByUserParams) ([]Intervention, error)
	ListPendingRuns(ctx context.Context, limit int32) ([]Run, error)
	ListRunsByArtifact(ctx context.Context, arg ListRunsByArtifactParams) ([]Run, error)
	ListRunsByUser(ctx context.Context, arg ListRunsByUserParams) ([]Run, error)
	UpdateArtifact(ctx context.Context, arg UpdateArtifactParams) (Artifact, error)
	UpdateArtifactContent(ctx context.Context, arg UpdateArtifactContentParams) (Artifact, error)
	UpdateLearningProfileStats(ctx context.Context, arg UpdateLearningProfileStatsParams) (LearningProfile, error)
	UpdateRunOutput(ctx context.Context, arg UpdateRunOutputParams) (Run, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error)
	UpdateTopicSkills(ctx context.Context, arg UpdateTopicSkillsParams) (LearningProfile, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertLearningProfile(ctx context.Context, arg UpsertLearningProfileParams) (LearningProfile, error)
}

var _ Querier = (*Queries)(nil)
