// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package storage

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countRunsByUser = `-- name: CountRunsByUser :one
SELECT COUNT(*) FROM runs
WHERE user_id = $1
`

func (q *Queries) CountRunsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuccessfulRunsByUser = `-- name: CountSuccessfulRunsByUser :one
SELECT COUNT(*) FROM runs
WHERE user_id = $1
AND status = 'completed'
AND output->>'testsFailed' = '0'
`

func (q *Queries) CountSuccessfulRunsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSuccessfulRunsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (artifact_id, user_id, exercise_id, status, recipe)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, artifact_id, user_id, exercise_id, status, recipe, output, started_at, finished_at, created_at
`

type CreateRunParams struct {
	ArtifactID uuid.UUID       `db:"artifact_id" json:"artifact_id"`
	UserID     uuid.UUID       `db:"user_id" json:"user_id"`
	ExerciseID sql.NullString  `db:"exercise_id" json:"exercise_id"`
	Status     string          `db:"status" json:"status"`
	Recipe     json.RawMessage `db:"recipe" json:"recipe"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ArtifactID,
		arg.UserID,
		arg.ExerciseID,
		arg.Status,
		arg.Recipe,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.UserID,
		&i.ExerciseID,
		&i.Status,
		&i.Recipe,
		&i.Output,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, artifact_id, user_id, exercise_id, status, recipe, output, started_at, finished_at, created_at FROM runs
WHERE id = $1
`

func (q *Queries) GetRunByID(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.UserID,
		&i.ExerciseID,
		&i.Status,
		&i.Recipe,
		&i.Output,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRunByIDAndUser = `-- name: GetRunByIDAndUser :one
SELECT id, artifact_id, user_id, exercise_id, status, recipe, output, started_at, finished_at, created_at FROM runs
WHERE id = $1 AND user_id = $2
`

type GetRunByIDAndUserParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetRunByIDAndUser(ctx context.Context, arg GetRunByIDAndUserParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunByIDAndUser, arg.ID, arg.UserID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.UserID,
		&i.ExerciseID,
		&i.Status,
		&i.Recipe,
		&i.Output,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingRuns = `-- name: ListPendingRuns :many
SELECT id, artifact_id, user_id, exercise_id, status, recipe, output, started_at, finished_at, created_at FROM runs
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingRuns(ctx context.Context, limit int32) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.UserID,
			&i.ExerciseID,
			&i.Status,
			&i.Recipe,
			&i.Output,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByArtifact = `-- name: ListRunsByArtifact :many
SELECT id, artifact_id, user_id, exercise_id, status, recipe, output, started_at, finished_at, created_at FROM runs
WHERE artifact_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRunsByArtifactParams struct {
	ArtifactID uuid.UUID `db:"artifact_id" json:"artifact_id"`
	Limit      int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListRunsByArtifact(ctx context.Context, arg ListRunsByArtifactParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByArtifact, arg.ArtifactID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.UserID,
			&i.ExerciseID,
			&i.Status,
			&i.Recipe,
			&i.Output,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByUser = `-- name: ListRunsByUser :many
SELECT id, artifact_id, user_id, exercise_id, status, recipe, output, started_at, finished_at, created_at FROM runs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsByUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListRunsByUser(ctx context.Context, arg ListRunsByUserParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.UserID,
			&i.ExerciseID,
			&i.Status,
			&i.Recipe,
			&i.Output,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunOutput = `-- name: UpdateRunOutput :one
UPDATE runs
SET status = $2,
    output = $3,
    finished_at = NOW()
WHERE id = $1
RETURNING id, artifact_id, user_id, exercise_id, status, recipe, output, started_at, finished_at, created_at
`

type UpdateRunOutputParams struct {
	ID     uuid.UUID             `db:"id" json:"id"`
	Status string                `db:"status" json:"status"`
	Output pqtype.NullRawMessage `db:"output" json:"output"`
}

func (q *Queries) UpdateRunOutput(ctx context.Context, arg UpdateRunOutputParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRunOutput, arg.ID, arg.Status, arg.Output)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.UserID,
		&i.ExerciseID,
		&i.Status,
		&i.Recipe,
		&i.Output,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $2,
    started_at = COALESCE($3, started_at),
    finished_at = COALESCE($4, finished_at)
WHERE id = $1
RETURNING id, artifact_id, user_id, exercise_id, status, recipe, output, started_at, finished_at, created_at
`

type UpdateRunStatusParams struct {
	ID         uuid.UUID    `db:"id" json:"id"`
	Status     string       `db:"status" json:"status"`
	StartedAt  sql.NullTime `db:"started_at" json:"started_at"`
	FinishedAt sql.NullTime `db:"finished_at" json:"finished_at"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRunStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.UserID,
		&i.ExerciseID,
		&i.Status,
		&i.Recipe,
		&i.Output,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
